Repository dsc-galgotias-university/gitTest, pull requests merged in 2019-06, with the labels that each got.

#91 Update info.csv
  info.csv
Labels: Ok

#104 Update info.csv
  info.csv
Labels: Ok

#114 Update info.csv
  info.csv
Labels: Ok

#112 Update info.csv
  info.csv
Labels: Ok

#111 Update info.csv
  info.csv
Labels: Ok

#101 Updated info.csv
  info.csv
Labels: Ok

#100 Update info.csv
  info.csv
Labels: Ok

#96 Update info.csv
  info.csv
Labels: Ok

#86 sakshi.8
  info.csv
Labels: Ok, help wanted

#110 updated info.csv
  info.csv
Labels: Ok

#36 Task for dsc confirmation
  info.csv
Labels: Ok, help wanted

#43 update info.csv
  info.csv
Labels: Ok, help wanted

#56 Update info.csv
  info.csv
Labels: Ok

#118 Update info.csv
  info.csv
Labels: Ok

#90 Sonam Singhal,18SCSE1010339
  info.csv
Labels: Ok

#89 Add files via upload
  info.csv
Labels: Ok

#47 Update info.csv
  info.csv
Labels: Ok

#83 Update info.csv
  info.csv
Labels: Ok

#59 Update info.csv
  info.csv
Labels: Ok, help wanted

#78 Adding info
  info.csv
Labels: Ok

#77 userdetails added
  info.csv
Labels: Ok

#75 NAGENDRA KUMAR INFO
  info.csv
Labels: Ok

#72 Updated info.csv
  info.csv
Labels: Ok

#68 Update info.csv
  info.csv
Labels: Ok

#67 Update info.csv
  info.csv
Labels: Ok

#62 Update info.csv
  info.csv
Labels: Ok

#58 Update info.csv
  info.csv
Labels: Ok

#61 Update info.csv
  info.csv
Labels: Ok, help wanted

#131 update.csv
  info.csv
Labels: Maybe: CRLF

#87 modified
  info.csv
Labels: Maybe: CRLF

#84 file modified
  info.csv
Labels: Maybe: CRLF

#32 update info.csv
  info.csv
Labels: Maybe: CRLF

#154 muskaan sharma,18scse1010168,18021011412,android dev,1st,5,py java c,…
  info.csv
Labels: Ok
